### ISSUE TITLE
bug: Wrong label

### ISSUE THREAD

**Issue by xEdziu** [Kubis10/CounterForMessenger#12]
# Expected Behaviour
Title in main view should be "Counter For Messenger"

# Actual Behaviour
Title is "Ustawienia"

# Version
0.1.0-beta

# Screenshots
![image](https://user-images.githubusercontent.com/50357817/154373419-2ab2589a-96ca-4d0c-a6c7-752dd8d26e8c.png)

**Comment by Kubis10** [comment]
Done
