### ISSUE TITLE
bug: Can't sort data if stopped loading

### ISSUE THREAD

**Issue by xEdziu** [Kubis10/CounterForMessenger#13]
**Describe the bug**
When you stop loading data by closing progress bar window, you can't sort already loaded data by number of messeages or call time

**To Reproduce**
1. Restart app
2. Try to load files several times

**Expected behavior**
You should be able to sort data that is already loaded

**Screenshots**
![image](https://user-images.githubusercontent.com/50357817/154374616-87efaef6-b253-4e89-ada4-7319d88fdff0.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version of app: 0.1.0-beta

**Additional context**
Console log:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1921, in __call__
  File "Main.py", line 231, in <lambda>
  File "Main.py", line 104, in countAll
  File "tkinter\__init__.py", line 1681, in cget
_tkinter.TclError: invalid command name ".!toplevel.!progressbar"
```

**Comment by Kubis10** [comment]
Fixed
