### ISSUE TITLE
idea: Show inbox path in app window, not console

### ISSUE THREAD

**Issue by xEdziu** [Kubis10/CounterForMessenger#14]
**Is your feature request related to a problem? Please describe.**
I think that app should display to user what path was chosen inside app window, not console

**Describe the solution you'd like**
After selecting directory, print out absolute path under the select dir button

**Additional context**
![image](https://user-images.githubusercontent.com/50357817/154375667-d356dd39-6879-432b-834f-6abc3cb8a5a9.png)

**Comment by Kubis10** [comment]
Done
