### ISSUE TITLE
bug: Unintentional button

### ISSUE THREAD

**Issue by xEdziu** [Kubis10/CounterForMessenger#15]
**Describe the bug**
This is not clearly a gambreaking bug, but it should not be like that - I am talking about confirm button while setting up first configuration

**To Reproduce**
1. Start app for first time

**Expected behavior**
Button should be wider and have some text on it

**Screenshots**
![image](https://user-images.githubusercontent.com/50357817/154427430-0d971def-c7a3-4e44-9f33-7e5963681561.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version of app 0.1.0-beta[pre-release]

**Comment by Kubis10** [comment]
Fixed, text was but you need to scroll. Now button is visible from beginning
