### ISSUE TITLE
idea: Make window wider on start

### ISSUE THREAD

**Issue by xEdziu** [Kubis10/CounterForMessenger#16]
**Is your feature request related to a problem? Please describe.**
I am frustrated when I have to manually resize app window to see the call time columns

**Describe the solution you'd like**
I would like app to be wider, so you don't have to do that

**Additional context**
Screenshot:
![image](https://user-images.githubusercontent.com/50357817/154427845-463772f1-dd8f-455c-97cf-6401cc56edff.png)

**Comment by Kubis10** [comment]
Fixed with new update
