### ISSUE TITLE
Hardcoded application language

### ISSUE THREAD

**Issue by Ezioleq** [Kubis10/CounterForMessenger#22]
**Is your feature request related to a problem? Please describe.**

Everything's fine but the whole app is in hardcoded polish language without any option to change it when the project's site is using english. Misleaded foreign users may not use this program simply because they will not understand the UI.

**Describe the solution you'd like**

Multi-language support. This should be fairly simple to implement for example by using json file with translated strings for every language.

**Describe alternatives you've considered**

Change hardcoded strings from polish to english.

**Comment by Kubis10** [comment]
Noted! I will add this in next update
