### ISSUE TITLE
Option to count by date

### ISSUE THREAD

**Issue by Kubis10** [Kubis10/CounterForMessenger#26]
Add option to not only count messages from all time, but to count by specific period of time

**Comment by ahmarhafeez1** [comment]
Hey Can I help with this issue?

**Comment by Kubis10** [comment]
@ahmarhafeez1 Sure I would appreciate any help

**Comment by ahmarhafeez1** [comment]
> @ahmarhafeez1 Sure I would appreciate any help

Alright I'll create a PR once I'm done

**Comment by RadoslavK1** [comment]
Hello, I solved this issue, will send a pull request today

**Comment by RadoslavK1** [comment]
> Hello, I solved this issue, will send a pull request today

PR sent.
