### ISSUE TITLE
Add better sorting

### ISSUE THREAD

**Issue by Kubis10** [Kubis10/CounterForMessenger#29]
Add better sorting method in main view (ex: add option to sort by chat type and messages count in the same time) and sort people in groups in "more stats" by default by messages count, add option to filter data.

**Comment by Abhijeet-1409** [comment]
can i take this issue ?

**Comment by Kubis10** [comment]
Sure

**Comment by cremick** [comment]
Hi, is this issue still open? I would love to work on it

**Comment by Kubis10** [comment]
@cremick  Hi, yes it is still open so if you have any questions, feel free to ask

**Comment by Coder2Mo** [comment]
if i may i will work on this too

**Comment by Kubis10** [comment]
No problem

**Comment by tkroening** [comment]
Hi!

We're a team of five looking to contribute to an open source project as part of our Software Engineering class. We were wondering if this issue is still a problem, and whether we could work on it?

Thank you for your time!

**Comment by Kubis10** [comment]
@tkroening Yes, the task is still to do. I would appreciate your help thanks!

**Comment by tkroening** [comment]
Our team has made some progress on the "sorting" component of this issue. See [this draft PR](https://github.com/tkroening/CounterForMessenger/pull/2) for a screenshot and a video demo. The new popup implemented in this PR  would allow users to sort on any arbitrary combination of columns they like.

What do you think? Are there any additional features or UI changes that we could add?

Thank you!

**Comment by tkroening** [comment]
Thank you for your feedback! I've updated the PR with some changes that try to implement your suggestions. Do the changes implement what you had in mind?

**Comment by Kubis10** [comment]
Now better, but reverse and remove buttons are not working

**Comment by tkroening** [comment]
Thank you for your reply! May I ask how to reproduce this issue? I only ask because the way I implemented those buttons was to read the selection from the left column.

I agree that this is pretty bad UX. There might be a way to detect which listbox is active, and have the buttons use that instead.

**Comment by Kubis10** [comment]
I get it now. I think it's not intuitive, and it won't be for people either, so it would be useful to somehow change the UI or give some hints on how it works

**Comment by Chen3018** [comment]
Just for clarification, is the filtering option for the main view? Or should it be for the statistic view as well?

**Comment by Kubis10** [comment]
Generally, the task was to make the messages sorted by default by the number of messages, the same in individual statistics for groups, etc., and to make the sorting options more advanced in the main view, as you have done now

**Comment by tkroening** [comment]
> it would be useful to somehow change the UI or give some hints on how it works

I agree! I think part of what makes it un-intuitive is that a user would expect to be able to use those buttons even when they've selected something in the right column.

So, my proposed solution is to check both columns for a selection when those buttons are pressed. Here's a demo:
[Demo](https://github.com/Kubis10/CounterForMessenger/assets/92952795/5685ee14-b997-4206-8045-2a23a379aa5a)

The PR has been updated with the code. Is this what you had in mind?

**Comment by Kubis10** [comment]
Now it's great, as for the code, I would only ask you to separate the entire text in the UI as values for translations and I think it will be okay with this part

**Comment by tkroening** [comment]
I've [updated](https://github.com/tkroening/CounterForMessenger/pull/2) the popup with support for localization, and added translations for the other languages. I used an LLM (Google Gemini) to generate the translations for the other languages, so I can't vouch for their correctness (except for the German). I've marked all of them as `"NEEDS REVIEW"`.

Would you rather I just leave in the original English strings or are those translations okay?

Another question our team had is whether we could help work on some of the other things mentioned in the original issue:
> add option to filter data

> sort people in groups in "more stats" by default by messages count

Would these still be helpful? Since we're a team of five, we could definitely try to work on a filtering feature, or improvements to the "More statistics" view.

Thank you again for your time!

**Comment by Kubis10** [comment]
Sure, I would appreciate your help with these subtasks. Thanks!

**Comment by tkroening** [comment]
I've made a PR (#56) that adds the sorting component mentioned in this issue. Let me know if I can make any changes.

Thank you!

**Comment by cathyxfeiyang** [comment]
I've updated the profile and statistics popups (linked in this PR: https://github.com/tkroening/CounterForMessenger/pull/3):
- profile: allow users to filter chat history data (number of messages and characters) by chat type (all, private, group)
- statistics: allow users to filter statistics displayed by message length minimums and maximums

Would these be helpful to the project? Let me know if I can make any changes. 

Thank you!
