### ISSUE TITLE
English language doesn't work

### ISSUE THREAD

**Issue by edkry** [Kubis10/CounterForMessenger#30]
**Describe the bug**
English language doesn't work

**To Reproduce**
1. Clone CounterForMessenger repo, branch - master
2. Run `python Main.py`
3. Switch to English language :: nothing happens

**Expected behavior**
Text of the application is in English

**Screenshots**
![image](https://user-images.githubusercontent.com/39278922/234073790-aca85984-1f81-476b-8cc5-5c7a273e6299.png)

If I select Polski instead, then I don't have an option to select English:
![image](https://user-images.githubusercontent.com/39278922/234074012-cae8d8ac-fe32-46af-bd5b-43cb98689c93.png)

**Desktop (please complete the following information):**
 - W10, Python 3.9.0
 
**Additional context**
Would be nice to have so I could start contributing

**Comment by Kubis10** [comment]
Hi! Firstly, thanks for reporting this bug and it should be fixed now
