### ISSUE TITLE
Interpolating the username through the given data

### ISSUE THREAD

**Issue by ippokratis12** [Kubis10/CounterForMessenger#41]
I noticed that we can find the username through the data without asking the user to type it. That way we can prevent any typos. From that aspect we can see that the configuration page isn't very usefull as everything can be done through the settings section. I'd like to tackle that problem for you if you'd like to and also i can add the german language.

**Comment by Kubis10** [comment]
Hi, sure, I would appreciate it

**Comment by ippokratis12** [comment]
I'm on it

**Comment by ippokratis12** [comment]
i've finished the issue. I made a commit but i can't push it. Also i don't know how to make a pull request so what should i do?

**Comment by ippokratis12** [comment]
I forgot to mention that i use pycharm. So when you can please tell what to do, in order to be able to show you the code and hopefully merge it to the main branch

**Comment by ippokratis12** [comment]
I found how to do i pull request through pycharm but it says i can't because i don't have permission or something. What should i do?

**Comment by Kubis10** [comment]
Hi, You need to create a pull request via github. I wrote how to do it in my guide for translators. https://github.com/Kubis10/CounterForMessenger/wiki/Complete-Guide-for-Translators

**Comment by ippokratis12** [comment]
ok i've done it

**Comment by ippokratis12** [comment]
I've made the commit and i made a new pull request, as you've seen i guess. Is everything ok about the code now?

**Comment by Kubis10** [comment]
You created another pull request unnecessarily, all you had to do was add a commit to that fork and everything would be updated, so which pull request is correct now?

**Comment by Kubis10** [comment]
I tested it, and it works good, but I think there should be loading popup because it takes too long for app to get name, and it froze whole app process

**Comment by ippokratis12** [comment]
I don't know how to use GitHub well, so I'm sorry about that. Both pull requests are the same. Basically i made a new commit to the previous fork. But when i did that, on top it had a button called "create a new pull request " so i pressed it (because i thought that i had to do another pull) and i made the new pull request. The codes are the same. Sorry for the confusion. Is it necessary to put a loading bar or something?

**Comment by Kubis10** [comment]
No problem, it would be great if you implement this

**Comment by ippokratis12** [comment]
i made the functionality. I made two commits cause the first time i didn't see it. It's the same code. Sorry again for the confusion. Check it when you can
