### ISSUE TITLE
bug: Can't unselect selection

### ISSUE THREAD

**Issue by xEdziu** [Kubis10/CounterForMessenger#8]
# Expected behaviour
After clicking elsewhere than list of conversations, selections should be cleared

# Actual behaviour
Selections (once selected anything) can't be unselected

# Steps to reproduce
1. Restart app

# Version
v0.1.0-alfa

# Screenshots
![image](https://user-images.githubusercontent.com/50357817/154123488-299d02b5-c4a7-4c55-86fc-97c9fd35014e.png)

# Console log (only in alpha releases)
Nothing userfull to show here

**Comment by Kubis10** [comment]
Fixed
